### ISSUE TITLE
Change color of default "Player Note" icon color

### ISSUE THREAD

**Issue by got2bhockey** [TempusOwl/bm-userscript#3]
I'm happy to submit a PR for this myself, but I wasn't sure which JS minifier you're using and didn't want to cause any issues with the small differences between code.js and code.min.js if there's a specific reason for that. This can be easily implemented by adding the following code. I'm not certain what the ideal color would be, but #FF201A (red) should offer the best visibility.

```

const colors = {
    cTeamBluefor: "#e7a600",
    cTeamOpfor: "rgb(217,86,39)",
    cAdminName: "#00fff7",
    cbmAdmin: "#58ff47",
    cModAction: "#ff3333",
    cAdminAction: "#37ff00",
    cTeamKilled: "#ffcc00",
    cLeftServer: "#ff33cc",
    cJoined: "#919191",
    cGrayed: "#919191",
    cTracked: "#FF931A",
    cNoteIcon: "#FF201A",
};

let noteIcon = document.querySelectorAll(".css-he5ni6");
    
// Apply color to the note icon
noteIcon.forEach((icon) => {
    icon.style.color = colors.cNoteIcon; // Apply the icon color
});
```

**Comment by got2bhockey** [comment]
Ref: https://github.com/TempusOwl/bm-userscript/pull/4

**Comment by Synarious** [comment]
Feature has been added in #5
